import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";
import ResponsiveNav from "@/component/Home/Navbar/ResponsiveNav";

//font-settings
const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "saklain Sahariar protfolio - build with the Next-js",
  description: "this protfolio is Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sora.variable} antialiased`}
      >
        <ResponsiveNav></ResponsiveNav>
        {children}
      </body>
    </html>
  );
}
