import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";
import TopLeftimg from "@/component/Helper/TopLeftimg/TopLeftimg";
import Nav from "@/component/Home/Navbar/Nav";

//font-settings
const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "saklain Sahariar protfolio - build with the Next-js",
  description: "this protfolio is Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-secondary overflow-hidden leading-relaxed">
        <div className={`w-full h-screen overflow-hidden bg-site h1 ${sora.variable} bg-cover bg-no-repeat font-sora relative`}>
          <TopLeftimg></TopLeftimg>
          <Nav></Nav>
          {children}
        </div>
      </body>
    </html>
  );
}
